"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { RecoilRoot } from "recoil";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  cartItemCount,
  onCartClick,
}: Readonly<{
  children: React.ReactNode;
  cartItemCount: number;
  onCartClick: () => void;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilRoot>
          <Navbar cartItemCount={cartItemCount} onCartClick={onCartClick} />
          <main style={{ padding: "20px" }}>{children}</main>
        </RecoilRoot>
      </body>
    </html>
  );
}
